// Serves robots.txt and sitemap.xml at the stgeorgesstrategy.com apex.
// Routes: stgeorgesstrategy.com/robots.txt and stgeorgesstrategy.com/sitemap.xml
// Deploy: npm run deploy:cloudflare:seo-route
//
// sitemap.xml is proxied from the Pages main branch (generated by
// scripts/generate_sitemap.mjs before each Pages deploy, so it includes
// archived editions automatically). PUBLIC_PAGES below is only the static
// fallback if the Pages fetch fails. URLs only — no hard-coded lastmod
// dates or counts, so nothing here goes stale between weekly refreshes.

const SITEMAP_ORIGIN = "https://st-georges-strategy-intelligence.pages.dev/sitemap.xml";

const PUBLIC_PAGES = [
  "https://stgeorgesstrategy.com/",
  "https://stgeorgesstrategy.com/brief/",
  "https://stgeorgesstrategy.com/signals/",
  "https://stgeorgesstrategy.com/signals/ai/",
  "https://stgeorgesstrategy.com/committee-questions/",
  "https://stgeorgesstrategy.com/archive/",
  "https://stgeorgesstrategy.com/about/",
];

const SITEMAP_XML = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${PUBLIC_PAGES.map((loc) => `  <url>\n    <loc>${loc}</loc>\n  </url>`).join("\n")}
</urlset>
`;

const ROBOTS_TXT = `User-agent: *
Allow: /

Sitemap: https://stgeorgesstrategy.com/sitemap.xml
`;

const SECURITY_HEADERS = {
  "x-content-type-options": "nosniff",
  "referrer-policy": "strict-origin-when-cross-origin",
  "strict-transport-security": "max-age=31536000; includeSubDomains; preload",
};

function respond(body, contentType) {
  return new Response(body, {
    status: 200,
    headers: {
      "content-type": contentType,
      "cache-control": "public, max-age=0, must-revalidate",
      "x-pvo-route": "stgeorgesstrategy-seo-files",
      ...SECURITY_HEADERS,
    },
  });
}

export default {
  async fetch(request) {
    if (!["GET", "HEAD"].includes(request.method)) {
      return new Response("Method not allowed", {
        status: 405,
        headers: { Allow: "GET, HEAD", ...SECURITY_HEADERS },
      });
    }

    const { pathname } = new URL(request.url);

    if (pathname === "/sitemap.xml") {
      try {
        const upstream = await fetch(SITEMAP_ORIGIN, {
          cf: { cacheTtl: 0, cacheEverything: false },
        });
        if (upstream.ok) {
          return respond(await upstream.text(), "application/xml; charset=utf-8");
        }
      } catch {
        // fall through to static fallback
      }
      return respond(SITEMAP_XML, "application/xml; charset=utf-8");
    }

    if (pathname === "/robots.txt") {
      return respond(ROBOTS_TXT, "text/plain; charset=utf-8");
    }

    return new Response("Not found", {
      status: 404,
      headers: { "content-type": "text/plain; charset=utf-8", ...SECURITY_HEADERS },
    });
  },
};
